"use client"

import BasePage from "../base";
import AddProduct from "./addproduct";
import { getColumns } from "./columns";
import { DataTable } from "./producttable";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs"
import { Product } from "../types";
import { useState } from "react";
import { Button } from "../components/ui/button";
import PriceListEditor from "./pricelist/priceListEditor";

export default function ProductsPage() {
    const [isCreatingPriceList, setIsCreatingPriceList] = useState(false);

    const head = <div className="flex flex-col gap-4">
        <div className="flex flex-row items-center justify-between">
            <h1 className="title"
            >Products</h1>
            <div className="flex gap-4">
                <Button onClick={() => { setIsCreatingPriceList(true) }}>
                    Create Price List
                </Button>
                <AddProduct />
            </div>
        </div>
        <hr className="border-b border-muted" />
    </div>

    // START
    const getData = (type: "all" | "available" | "archived") => {
        const date = new Date("2021-01-01T00:00:00Z")
        const data: Product[] = [
            {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            }, {
                code: "P001",
                image: "https://via.placeholder.com/150",
                warehouse: "Main",
                description: "Product 1",
                category: "Category 1",
                type: "Type 1",
                weight: 10,
                location: "A1",
                minStock: 10,
                reorderQty: 20,
                serialNo: "SN001",
                price: 100,
                tax: 10,
                unitOfSale: "Unit",
                supplier: "Supplier 1",
                quantity: 100,
                costPrice: 90,
                discount: 5,
                orderedDate: date,
                isDiscounted: true,
                taxState: true,
                created: date.toString()
            },
        ]

        return data;
    }
    // END

    const classNames = {
        parentDiv: "h-[65vh] overflow-auto",
        table: {
            header: "sticky top-0 bg-background z-10",
            body: "overflow-scroll z-0"
        }
    }

    return (
        <BasePage customHead={head} pageId={4} >
            {isCreatingPriceList && <PriceListEditor onClose={() => { setIsCreatingPriceList(false) }} />}
            <Tabs defaultValue="all" className="w-full">
                <TabsList>
                    <TabsTrigger value="all">All</TabsTrigger>
                    <TabsTrigger value="available">Available</TabsTrigger>
                    <TabsTrigger value="archived">Archived</TabsTrigger>
                </TabsList>
                <TabsContent value="all">
                    <DataTable data={getData("all")} columns={getColumns()} classNames={classNames} />
                </TabsContent>
                <TabsContent value="available">
                    <DataTable data={getData("available")} columns={getColumns()} classNames={classNames} />
                </TabsContent>
                <TabsContent value="archived">
                    <DataTable data={getData("archived")} columns={getColumns()} classNames={classNames} />
                </TabsContent>
            </Tabs>
        </BasePage>
    )
}